version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 37017:27017

  quovote-backend:
    image: quovote-backend
    build:
      context: backend
      dockerfile: dev.Dockerfile
    environment:
      - FRONTEND_BASE_PATH=http://${DOMAIN:-stack.localhost}
      - BACKEND_BASE_PATH=http://${DOMAIN:-stack.localhost}/api
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=(Host(`${DOMAIN:-stack.localhost}`) && (PathPrefix(`/api`) || PathPrefix(`/socket`)))'
      - 'traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api'
      - 'traefik.http.routers.backend.middlewares=backend-stripprefix@docker'
      - 'traefik.http.routers.backend.entrypoints=web'
    expose:
      - 3000
    volumes:
      - ./backend/src:/app/src

  quovote-frontend:
    image: quovote-frontend
    build:
      context: frontend
      dockerfile: dev.Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(`${DOMAIN:-stack.localhost}`)'
      - 'traefik.http.routers.frontend.entrypoints=web'
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    expose:
      - 8080

  load-balancer:
    image: traefik:v2.2
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
